- name: Deploy Kubernetes Master Component
  hosts: master
#  sudo: True
  become: true
  become_user: root
  tasks:
  - name: copy controller-manager
    copy: src=../bin/kubernetes/kube-controller-manager  dest=/usr/bin mode=700

  - name: copy controller-manager.yml
    copy: src=../svc/controller-manager.service  dest=/etc/systemd/system/controller-manager.service

  - name: start controller-manager
    systemd: name=controller-manager enabled=yes daemon-reload=yes state=restarted 
