- name: Deploy Kubernetes Master Component
  hosts: node
#  sudo: True
  become: true
  become_user: root
  tasks:
  - name: copy kubelet
    copy: src=../bin/kubernetes/kubelet  dest=/usr/bin mode=700

  - name: copy kubelet.service
    copy: src=../svc/kubelet.service  dest=/etc/systemd/system/kubelet.service

  - name: kubelet
    systemd: name=kubelet enabled=yes daemon-reload=yes state=restarted 
