- name: Deploy Kubernetes Master Component
  hosts: node
#  sudo: True
  become: true
  become_user: root
  tasks:
  - name: copy proxy
    copy: src=../bin/kubernetes/kube-proxy  dest=/usr/bin mode=700

  - name: copy proxy.yml
    copy: src=../svc/proxy.service  dest=/etc/systemd/system/proxy.service

  - name: start proxy
    systemd: name=proxy enabled=yes daemon-reload=yes state=restarted 
